name: yt-dlp
summary: A fork of youtube-dl with additional features and patches 
description: |
      Based on youtube-dl 2021.06.06 commit/379f52a and 
      youtube-dlc 2020.11.11-3 commit/98e248f, youtube-dl offers all the
      features and patches of youtube-dlc in addition to the latest youtube-dl
adopt-info: yt-dlp
grade: stable 
confinement: strict
base: core22
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  yt-dlp:
    command: bin/yt-dlp
    plugs: [home, network, network-bind, removable-media]
    environment:
environment:
  "LD_LIBRARY_PATH": "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"

parts:
  yt-dlp:
    plugin: python
    source: https://github.com/yt-dlp/yt-dlp.git
    #source-tag: '2023.10.13'
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags)
    stage-packages:
      - libavdevice58
      - libblas3
      - ffmpeg
      - libpulse0
      - python3-certifi
